version: '3.8'

services:
  website:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: giwu_website
    environment:
      - ASPNETCORE_ENVIRONMENT=UAT
    networks:
      - webnet

networks:
  webnet:
    external: true
